version: '3.7'

services:
  app:
    container_name: voila-template-tags
    image: voila-template-tags-dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./share/jupyter/voila/templates:/root/.local/share/jupyter/voila/templates
      - ./notebooks:/home/voila/notebooks
    ports:
      - 8866:8866
    environment:
      - VOILA_NOTEBOOK
    command: "pipenv run voila --template {{ cookiecutter.template_name }} $VOILA_NOTEBOOK"
